<?xml version="1.0" encoding="UTF-8"?>
<!--

    Sonatype Nexus (TM) Open Source Version
    Copyright (c) 2008-present Sonatype, Inc.
    All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.

    This program and the accompanying materials are made available under the terms of the Eclipse Public License Version 1.0,
    which accompanies this distribution and is available at http://www.eclipse.org/legal/epl-v10.html.

    Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
    of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
    Eclipse Foundation. All other trademarks are the property of their respective owners.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.sonatype.nexus.selfhosted.assemblies</groupId>
    <artifactId>nexus-selfhosted-assemblies-parent</artifactId>
    <version>3.93.2-01</version>
  </parent>

  <artifactId>nexus-repository-core</artifactId>
  <name>${project.groupId}:${project.artifactId}</name>
  <packaging>jar</packaging>

  <dependencies>
    <dependency>
      <groupId>org.sonatype.nexus.common.assemblies</groupId>
      <artifactId>nexus-base-overlay</artifactId>
      <type>zip</type>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-configuration</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-spring</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-common</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-bootstrap-spring</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-extender-spring</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.selfhosted.components</groupId>
      <artifactId>nexus-repository-core-edition</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-logging</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard.metrics</groupId>
      <artifactId>metrics-core</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard.metrics</groupId>
      <artifactId>metrics-httpclient</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard.metrics</groupId>
      <artifactId>metrics-servlets</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard.metrics</groupId>
      <artifactId>metrics-servlet</artifactId>
    </dependency>
    <dependency>
      <groupId>io.prometheus</groupId>
      <artifactId>simpleclient_dropwizard</artifactId>
    </dependency>
    <dependency>
      <groupId>io.prometheus</groupId>
      <artifactId>simpleclient_servlet</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.velocity</groupId>
      <artifactId>velocity-engine-core</artifactId>
    </dependency>

    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-jmx</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee8</groupId>
      <artifactId>jetty-ee8-servlet</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.eclipse.jetty.ee8</groupId>
          <artifactId>jetty-ee8-nested</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>net.java.dev.jna</groupId>
      <artifactId>jna-platform</artifactId>
      <scope>runtime</scope>
    </dependency>
    <!-- overridden dependencies -->
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>jcl-over-slf4j</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>log4j-over-slf4j</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>jul-to-slf4j</artifactId>
    </dependency>
    <!-- components -->
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-audit</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-base</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-blobstore</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-blobstore-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-blobstore-file</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-cache</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-capability</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-cleanup</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-cleanup-config</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-crypto</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-datastore</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-datastore-h2</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-datastore-mybatis</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-distributed-event-service-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-search-sql</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-email</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-extdirect</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-formfields</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-httpclient</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-jetty-log</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-jmx</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-mime</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-plugin-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-quartz</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-rapture</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-repository-config</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-repository-content</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-repository-services</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-repository-view</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-rest</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-rest-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-rest-jackson2</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-scheduling</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-script</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-security</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-selector</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.selfhosted.components</groupId>
      <artifactId>nexus-self-hosted</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-servlet</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-siesta</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-ssl</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-supportzip-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-swagger</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-thread</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-transaction</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-ui-plugin</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-upgrade</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-validation</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-webhooks</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-webresources-api</artifactId>
    </dependency>

    <!-- plugins -->

    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-audit-plugin</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-blobstore-s3</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-blobstore-tasks</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-coreui-plugin</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-default-role-plugin</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-onboarding-plugin</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-repository-apt</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-repository-httpbridge</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-repository-maven</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-repository-raw</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-script-plugin</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-ssl-plugin</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-task-log-cleanup</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-api-extdirect-common</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.selfhosted.components</groupId>
      <artifactId>nexus-api-extdirect-selfhosted</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-api-rest-common</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.selfhosted.components</groupId>
      <artifactId>nexus-api-rest-selfhosted</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.nexus.common.components</groupId>
      <artifactId>nexus-test-common</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.reflections</groupId>
      <artifactId>reflections</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <executions>
          <execution>
            <id>enforce-dependencies</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <fail>true</fail>
              <rules>
                <bannedDependencies>
                  <searchTransitive>true</searchTransitive>
                  <excludes combine.children="append">
                    <!-- Ban private -->
                    <exclude>com.sonatype.nexus*</exclude>
                  </excludes>
                </bannedDependencies>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <configuration>
          <excludePackageNames>org.sonatype.nexus.bootstrap.*</excludePackageNames>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>uberjar</id>
            <phase>package</phase>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <configuration>
          <executable>java</executable>
          <workingDirectory>${project.build.directory}/assembly</workingDirectory>
          <arguments>
            <argument>-jar</argument>
            <argument>${project.build.directory}/${project.build.finalName}.jar</argument>
          </arguments>
          <environmentVariables>
            <!-- Used by the `?debug` mode to allow javascript resources to be loaded from the filesystem -->
            <NEXUS_RESOURCE_DIRS>
              ${project.parent.parent.parent.parent.basedir}/public/common/components/nexus-base/src/main/resources,
              ${project.parent.parent.parent.parent.basedir}/public/common/components/nexus-coreui-plugin/src/main/resources,
              ${project.parent.parent.parent.parent.basedir}/public/common/components/nexus-coreui-plugin/target/classes,
              ${project.parent.parent.parent.parent.basedir}/public/common/components/nexus-example-content/src/main/resources,
              ${project.parent.parent.parent.parent.basedir}/public/common/components/nexus-onboarding-plugin/src/main/resources,
              ${project.parent.parent.parent.parent.basedir}/public/common/components/nexus-rapture/src/main/resources,
              ${project.parent.parent.parent.parent.basedir}/public/common/components/nexus-rapture/target/classes,
              ${project.parent.parent.parent.parent.basedir}/public/common/components/nexus-ui-plugin/target/classes,
              ${project.parent.parent.parent.parent.basedir}/public/common/components/formats/nexus-repository-maven/src/main/resources
            </NEXUS_RESOURCE_DIRS>
            <!-- Used to disable the random password generation, and default to admin/admin123 for easy development -->
            <NEXUS_SECURITY_RANDOMPASSWORD>false</NEXUS_SECURITY_RANDOMPASSWORD>
          </environmentVariables>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions>
          <!-- parent pom sets this execution up in pluginManagement, so it will autorun by including the plugin-->
          <!-- which we don't want for this assembly as we have our own antrun execution doing the work -->
          <execution>
            <id>overlay-assembly</id>
            <configuration>
              <skip>true</skip>
            </configuration>
          </execution>
          <execution>
            <id>customize-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <unzip src="${org.sonatype.nexus.common.assemblies:nexus-base-overlay:zip}"
                       dest="${project.build.directory}/assembly"
                       overwrite="true">
                  <patternset>
                    <exclude name="*/lib/**"/>
                    <exclude name="sonatype-work/**"/>
                  </patternset>
                  <cutdirsmapper dirs="1"/>
                </unzip>

                <unzip src="${org.sonatype.nexus.common.assemblies:nexus-base-overlay:zip}"
                       dest="${project.build.directory}/sonatype-work"
                       overwrite="true">
                  <patternset>
                    <include name="sonatype-work/**"/>
                  </patternset>
                  <cutdirsmapper dirs="1"/>
                </unzip>

                <!-- overlay customizations; failonerror is set because any copy fails on an empty folder -->
                <!-- preserving the command to stay consistent with other distributions and in case we re-add files -->
                <copy todir="${project.build.directory}/assembly" overwrite="true" failonerror="false">
                  <fileset dir="${project.basedir}/src/main/assembly/overlay"/>
                </copy>

                <!-- workaround maven-assembly-plugin bug where lineEnding configuration for fileSets is ineffective -->
                <fixcrlf srcdir="${project.build.directory}/assembly/bin" includes="*" excludes="*.bat" eol="unix"/>
                <fixcrlf srcdir="${project.build.directory}/assembly/bin" includes="*.bat" eol="dos"/>

                <!-- and don't forget the uberjar -->
                <copy file="${project.build.directory}/${project.artifactId}-${project.version}.jar"
                      todir="${project.build.directory}/assembly/bin" overwrite="true"/>
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>run</id>
      <build>
        <defaultGoal>exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>run-after-package</id>
                <phase>package</phase>
                <goals>
                  <goal>exec</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
