/*
 * Sonatype Nexus (TM) Open Source Version
 * Copyright (c) 2008-present Sonatype, Inc.
 * All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License Version 1.0,
 * which accompanies this distribution and is available at http://www.eclipse.org/legal/epl-v10.html.
 *
 * Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
 * of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
 * Eclipse Foundation. All other trademarks are the property of their respective owners.
 */
package org.sonatype.nexus.validation.internal;

import java.lang.reflect.Constructor;
import java.lang.reflect.Executable;
import java.lang.reflect.Method;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

import com.thoughtworks.paranamer.Paranamer;
import org.hibernate.validator.parameternameprovider.ParanamerParameterNameProvider;

/**
 * AOP-aware {@link ParanamerParameterNameProvider}.
 *
 * @since 3.0
 */
public class AopAwareParanamerParameterNameProvider
    extends ParanamerParameterNameProvider
{
  public AopAwareParanamerParameterNameProvider() {
    // empty
  }

  public AopAwareParanamerParameterNameProvider(final Paranamer paranamer) {
    super(paranamer);
  }

  /**
   * Class-name token which indicates class is synthetic generated by Guice AOP.
   */
  private static final String GUICE_ENHANCED = "$$EnhancerByGuice$$";

  /**
   * Cache for resolved constructors and methods to avoid repeated NoSuchMethodException on proxied types.
   * Keyed by the original executable (Constructor or Method), stores the resolved executable.
   * Bounded by the number of distinct validated method signatures across proxied classes.
   * Cast safety: {@link #resolveUncached} always returns the same runtime type as its input, so
   * retrieval casts back to {@code Constructor<?>} / {@code Method} are safe.
   * <p>
   * <b>Lifetime note:</b> entries strongly reference {@link Method} / {@link Constructor}, which in
   * turn pin their declaring {@code Class} and {@code ClassLoader}. NXRM does not unload plugin
   * classloaders at runtime, so this cache cannot leak Metaspace. If that assumption ever changes
   * (hot redeploy, dynamic plugin disable), swap this for a {@code Caffeine}/{@code Guava} cache
   * with {@code weakKeys().weakValues()}.
   */
  private final ConcurrentHashMap<Executable, Executable> resolvedCache = new ConcurrentHashMap<>();

  private static boolean isEnhancedSubclass(final Class<?> type) {
    return type.getName().contains(GUICE_ENHANCED);
  }

  @Override
  public List<String> getParameterNames(final Constructor<?> constructor) {
    return super.getParameterNames(resolve(constructor));
  }

  /**
   * Resolve constructor for synthetic classes generated by AOP platforms.
   */
  private Constructor<?> resolve(final Constructor<?> constructor) {
    return (Constructor<?>) resolvedCache.computeIfAbsent(constructor, this::resolveUncached);
  }

  @Override
  public List<String> getParameterNames(final Method method) {
    return super.getParameterNames(resolve(method));
  }

  /**
   * Resolve method for synthetic classes generated by AOP platforms.
   */
  private Method resolve(final Method method) {
    return (Method) resolvedCache.computeIfAbsent(method, this::resolveUncached);
  }

  /**
   * Core resolution logic: if the executable belongs to a Guice-enhanced subclass, look up the
   * equivalent executable on the real superclass; otherwise return the executable unchanged.
   * Used as the cache-miss loader for {@link #resolvedCache}.
   */
  private Executable resolveUncached(final Executable executable) {
    Class<?> type = executable.getDeclaringClass();
    if (isEnhancedSubclass(type)) {
      try {
        if (executable instanceof Constructor) {
          return type.getSuperclass().getDeclaredConstructor(executable.getParameterTypes());
        }
        else {
          Method m = (Method) executable;
          return type.getSuperclass().getDeclaredMethod(m.getName(), m.getParameterTypes());
        }
      }
      catch (NoSuchMethodException e) {
        // fall through to return original
      }
    }
    return executable;
  }
}
