/*
 * Sonatype Nexus (TM) Open Source Version
 * Copyright (c) 2008-present Sonatype, Inc.
 * All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License Version 1.0,
 * which accompanies this distribution and is available at http://www.eclipse.org/legal/epl-v10.html.
 *
 * Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
 * of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
 * Eclipse Foundation. All other trademarks are the property of their respective owners.
 */
package org.sonatype.nexus.swagger.internal;

// NEXUS-46395: ported from Swagger 1.x (io.swagger.models.*) to OpenAPI 3.x
// (io.swagger.v3.oas.models.*) when origin/main's NEXUS-48375 commit was integrated
// into the EE10 branch.
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.PathItem;
import io.swagger.v3.oas.models.PathItem.HttpMethod;
import org.junit.Before;
import org.junit.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

/**
 * Test for {@link OperationIdSwaggerContributor}.
 */
public class OperationIdSwaggerContributorTest
{
  private OperationIdSwaggerContributor underTest;

  @Before
  public void setup() {
    underTest = new OperationIdSwaggerContributor();
  }

  @Test
  public void postRepositoryPath_generatesCamelCaseCreateId() {
    OpenAPI swagger = swaggerWithOperation("/v1/repositories/maven/proxy", HttpMethod.POST);

    underTest.contribute(swagger);

    assertThat(operationId(swagger, "/v1/repositories/maven/proxy", HttpMethod.POST),
        is("createRepositoriesMavenProxy"));
  }

  @Test
  public void putRepositoryPathWithParam_generatesUpdateId() {
    OpenAPI swagger = swaggerWithOperation("/v1/repositories/maven/proxy/{repositoryName}", HttpMethod.PUT);

    underTest.contribute(swagger);

    assertThat(operationId(swagger, "/v1/repositories/maven/proxy/{repositoryName}", HttpMethod.PUT),
        is("updateRepositoriesMavenProxy"));
  }

  @Test
  public void getRepositoryPathWithParam_generatesGetId() {
    OpenAPI swagger = swaggerWithOperation("/v1/repositories/maven/proxy/{repositoryName}", HttpMethod.GET);

    underTest.contribute(swagger);

    assertThat(operationId(swagger, "/v1/repositories/maven/proxy/{repositoryName}", HttpMethod.GET),
        is("getRepositoriesMavenProxy"));
  }

  @Test
  public void getRepositoryPathWithoutParam_generatesListId() {
    OpenAPI swagger = swaggerWithOperation("/v1/repositories", HttpMethod.GET);

    underTest.contribute(swagger);

    assertThat(operationId(swagger, "/v1/repositories", HttpMethod.GET), is("listRepositories"));
  }

  @Test
  public void deleteRepositoryPathWithParam_generatesDeleteId() {
    OpenAPI swagger = swaggerWithOperation("/v1/repositories/{repositoryName}", HttpMethod.DELETE);

    underTest.contribute(swagger);

    assertThat(operationId(swagger, "/v1/repositories/{repositoryName}", HttpMethod.DELETE),
        is("deleteRepositories"));
  }

  @Test
  public void pathWithHyphens_convertsToPascalCase() {
    OpenAPI swagger = swaggerWithOperation("/v1/blobstores/azure-cloud", HttpMethod.POST);

    underTest.contribute(swagger);

    assertThat(operationId(swagger, "/v1/blobstores/azure-cloud", HttpMethod.POST),
        is("createBlobstoresAzureCloud"));
  }

  @Test
  public void betaPath_skipsBetaVersionSegment() {
    OpenAPI swagger = swaggerWithOperation("/beta/repositories/maven/proxy", HttpMethod.POST);

    underTest.contribute(swagger);

    assertThat(operationId(swagger, "/beta/repositories/maven/proxy", HttpMethod.POST),
        is("createRepositoriesMavenProxy"));
  }

  @Test
  public void existingAutoGeneratedOperationId_isOverwritten() {
    OpenAPI swagger = new OpenAPI();
    PathItem path = new PathItem();
    Operation op = new Operation();
    op.setOperationId("createRepository_2");
    path.operation(HttpMethod.POST, op);
    swagger.path("/v1/repositories/maven/proxy", path);

    underTest.contribute(swagger);

    assertThat(operationId(swagger, "/v1/repositories/maven/proxy", HttpMethod.POST),
        is("createRepositoriesMavenProxy"));
  }

  @Test
  public void nullPaths_doesNotThrow() {
    OpenAPI swagger = new OpenAPI();
    swagger.setPaths(null);

    underTest.contribute(swagger);
    // no exception expected
  }

  @Test
  public void patchOperation_generatesUpdateId() {
    OpenAPI swagger = swaggerWithOperation("/v1/security/users/{userId}", HttpMethod.PATCH);

    underTest.contribute(swagger);

    assertThat(operationId(swagger, "/v1/security/users/{userId}", HttpMethod.PATCH),
        is("updateSecurityUsers"));
  }

  @Test
  public void multipleOperationsOnSamePath_eachGetsUniqueId() {
    OpenAPI swagger = new OpenAPI();
    PathItem path = new PathItem();
    path.operation(HttpMethod.POST, new Operation());
    path.operation(HttpMethod.GET, new Operation());
    swagger.path("/v1/blobstores", path);

    underTest.contribute(swagger);

    assertThat(operationId(swagger, "/v1/blobstores", HttpMethod.POST), is("createBlobstores"));
    assertThat(operationId(swagger, "/v1/blobstores", HttpMethod.GET), is("listBlobstores"));
  }

  @Test
  public void nullPathEntry_doesNotThrow() {
    OpenAPI swagger = new OpenAPI();
    swagger.path("/v1/test", null);

    underTest.contribute(swagger);
    // no exception expected
  }

  @Test
  public void nullOperationMap_doesNotThrow() {
    OpenAPI swagger = new OpenAPI();
    PathItem path = new PathItem();
    // Don't set any operations, leaving operationMap as null
    swagger.path("/v1/test", path);

    underTest.contribute(swagger);
    // no exception expected
  }

  // --- helpers ---

  private static OpenAPI swaggerWithOperation(final String path, final HttpMethod method) {
    OpenAPI openApi = new OpenAPI();
    PathItem pathItem = new PathItem();
    pathItem.operation(method, new Operation());
    openApi.path(path, pathItem);
    return openApi;
  }

  private static String operationId(final OpenAPI openApi, final String path, final HttpMethod method) {
    return openApi.getPaths().get(path).readOperationsMap().get(method).getOperationId();
  }
}
