/*
 * Sonatype Nexus (TM) Open Source Version
 * Copyright (c) 2008-present Sonatype, Inc.
 * All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License Version 1.0,
 * which accompanies this distribution and is available at http://www.eclipse.org/legal/epl-v10.html.
 *
 * Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
 * of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
 * Eclipse Foundation. All other trademarks are the property of their respective owners.
 */
package org.sonatype.timeline.proto;

//Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: resources/proto/timelinerecord.proto

public final class TimeLineRecordProtos {
  private TimeLineRecordProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TimeLineRecordOrBuilder extends
                                           // @@protoc_insertion_point(interface_extends:timeline.TimeLineRecord)
                                               com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>optional string type = 2;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional string type = 2;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>optional string type = 2;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
    getTypeBytes();

    /**
     * <code>optional string subType = 3;</code>
     * @return Whether the subType field is set.
     */
    boolean hasSubType();
    /**
     * <code>optional string subType = 3;</code>
     * @return The subType.
     */
    java.lang.String getSubType();
    /**
     * <code>optional string subType = 3;</code>
     * @return The bytes for subType.
     */
    com.google.protobuf.ByteString
    getSubTypeBytes();

    /**
     * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
     */
    java.util.List<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data>
    getDataList();
    /**
     * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
     */
    org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data getData(int index);
    /**
     * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
     */
    java.util.List<? extends org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder>
    getDataOrBuilderList();
    /**
     * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
     */
    org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder getDataOrBuilder(
        int index);

    /**
     * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
     */
    java.util.List<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data>
    getKeywordsList();
    /**
     * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
     */
    org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data getKeywords(int index);
    /**
     * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
     */
    int getKeywordsCount();
    /**
     * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
     */
    java.util.List<? extends org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder>
    getKeywordsOrBuilderList();
    /**
     * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
     */
    org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder getKeywordsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code timeline.TimeLineRecord}
   */
  public static final class TimeLineRecord extends
                                           com.google.protobuf.GeneratedMessageV3 implements
                                                                                  // @@protoc_insertion_point(message_implements:timeline.TimeLineRecord)
                                                                                      TimeLineRecordOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use TimeLineRecord.newBuilder() to construct.
    private TimeLineRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TimeLineRecord() {
      type_ = "";
      subType_ = "";
      data_ = java.util.Collections.emptyList();
      keywords_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TimeLineRecord();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TimeLineRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              type_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              subType_ = bs;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                data_ = new java.util.ArrayList<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data>();
                mutable_bitField0_ |= 0x00000008;
              }
              data_.add(
                  input.readMessage(org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.PARSER, extensionRegistry));
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                keywords_ = new java.util.ArrayList<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data>();
                mutable_bitField0_ |= 0x00000010;
              }
              keywords_.add(
                  input.readMessage(org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          keywords_ = java.util.Collections.unmodifiableList(keywords_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return org.sonatype.timeline.proto.TimeLineRecordProtos.internal_static_timeline_TimeLineRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return org.sonatype.timeline.proto.TimeLineRecordProtos.internal_static_timeline_TimeLineRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.class, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Builder.class);
    }

    public interface DataOrBuilder extends
                                   // @@protoc_insertion_point(interface_extends:timeline.TimeLineRecord.Data)
                                       com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string key = 1;</code>
       * @return Whether the key field is set.
       */
      boolean hasKey();
      /**
       * <code>required string key = 1;</code>
       * @return The key.
       */
      java.lang.String getKey();
      /**
       * <code>required string key = 1;</code>
       * @return The bytes for key.
       */
      com.google.protobuf.ByteString
      getKeyBytes();

      /**
       * <code>optional string value = 2;</code>
       * @return Whether the value field is set.
       */
      boolean hasValue();
      /**
       * <code>optional string value = 2;</code>
       * @return The value.
       */
      java.lang.String getValue();
      /**
       * <code>optional string value = 2;</code>
       * @return The bytes for value.
       */
      com.google.protobuf.ByteString
      getValueBytes();
    }
    /**
     * Protobuf type {@code timeline.TimeLineRecord.Data}
     */
    public static final class Data extends
                                   com.google.protobuf.GeneratedMessageV3 implements
                                                                          // @@protoc_insertion_point(message_implements:timeline.TimeLineRecord.Data)
                                                                              DataOrBuilder {
      private static final long serialVersionUID = 0L;
      // Use Data.newBuilder() to construct.
      private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Data() {
        key_ = "";
        value_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Data();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Data(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                key_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                value_ = bs;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return org.sonatype.timeline.proto.TimeLineRecordProtos.internal_static_timeline_TimeLineRecord_Data_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return org.sonatype.timeline.proto.TimeLineRecordProtos.internal_static_timeline_TimeLineRecord_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.class, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder.class);
      }

      private int bitField0_;
      public static final int KEY_FIELD_NUMBER = 1;
      private volatile java.lang.Object key_;
      /**
       * <code>required string key = 1;</code>
       * @return Whether the key field is set.
       */
      @java.lang.Override
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string key = 1;</code>
       * @return The key.
       */
      @java.lang.Override
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string key = 1;</code>
       * @return The bytes for key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
      getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private volatile java.lang.Object value_;
      /**
       * <code>optional string value = 2;</code>
       * @return Whether the value field is set.
       */
      @java.lang.Override
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       * @return The bytes for value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
      getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
          return true;
        }
        if (!(obj instanceof org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data)) {
          return super.equals(obj);
        }
        org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data other = (org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data) obj;

        if (hasKey() != other.hasKey()) return false;
        if (hasKey()) {
          if (!getKey()
              .equals(other.getKey())) return false;
        }
        if (hasValue() != other.hasValue()) return false;
        if (hasValue()) {
          if (!getValue()
              .equals(other.getValue())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasKey()) {
          hash = (37 * hash) + KEY_FIELD_NUMBER;
          hash = (53 * hash) + getKey().hashCode();
        }
        if (hasValue()) {
          hash = (37 * hash) + VALUE_FIELD_NUMBER;
          hash = (53 * hash) + getValue().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code timeline.TimeLineRecord.Data}
       */
      public static final class Builder extends
                                        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                                                                                                // @@protoc_insertion_point(builder_implements:timeline.TimeLineRecord.Data)
                                                                                                    org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
          return org.sonatype.timeline.proto.TimeLineRecordProtos.internal_static_timeline_TimeLineRecord_Data_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
          return org.sonatype.timeline.proto.TimeLineRecordProtos.internal_static_timeline_TimeLineRecord_Data_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.class, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder.class);
        }

        // Construct using org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
          return org.sonatype.timeline.proto.TimeLineRecordProtos.internal_static_timeline_TimeLineRecord_Data_descriptor;
        }

        @java.lang.Override
        public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data getDefaultInstanceForType() {
          return org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.getDefaultInstance();
        }

        @java.lang.Override
        public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data build() {
          org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data buildPartial() {
          org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data result = new org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) != 0)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data) {
            return mergeFrom((org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data other) {
          if (other == org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.getDefaultInstance()) return this;
          if (other.hasKey()) {
            bitField0_ |= 0x00000001;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasValue()) {
            bitField0_ |= 0x00000002;
            value_ = other.value_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasKey()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object key_ = "";
        /**
         * <code>required string key = 1;</code>
         * @return Whether the key field is set.
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required string key = 1;</code>
         * @return The key.
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              key_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         * @return The bytes for key.
         */
        public com.google.protobuf.ByteString
        getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         * @param value The key to set.
         * @return This builder for chaining.
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         * @param value The bytes for key to set.
         * @return This builder for chaining.
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object value_ = "";
        /**
         * <code>optional string value = 2;</code>
         * @return Whether the value field is set.
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional string value = 2;</code>
         * @return The value.
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              value_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string value = 2;</code>
         * @return The bytes for value.
         */
        public com.google.protobuf.ByteString
        getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string value = 2;</code>
         * @param value The value to set.
         * @return This builder for chaining.
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string value = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>optional string value = 2;</code>
         * @param value The bytes for value to set.
         * @return This builder for chaining.
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:timeline.TimeLineRecord.Data)
      }

      // @@protoc_insertion_point(class_scope:timeline.TimeLineRecord.Data)
      private static final org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data();
      }

      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Data>
          PARSER = new com.google.protobuf.AbstractParser<Data>() {
        @java.lang.Override
        public Data parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Data(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Data> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Data> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object type_;
    /**
     * <code>optional string type = 2;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string type = 2;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBTYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object subType_;
    /**
     * <code>optional string subType = 3;</code>
     * @return Whether the subType field is set.
     */
    @java.lang.Override
    public boolean hasSubType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string subType = 3;</code>
     * @return The subType.
     */
    @java.lang.Override
    public java.lang.String getSubType() {
      java.lang.Object ref = subType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          subType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string subType = 3;</code>
     * @return The bytes for subType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getSubTypeBytes() {
      java.lang.Object ref = subType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private java.util.List<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data> data_;
    /**
     * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
     */
    @java.lang.Override
    public java.util.List<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder>
    getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
     */
    @java.lang.Override
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
     */
    @java.lang.Override
    public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
     */
    @java.lang.Override
    public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    public static final int KEYWORDS_FIELD_NUMBER = 5;
    private java.util.List<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data> keywords_;
    /**
     * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
     */
    @java.lang.Override
    public java.util.List<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data> getKeywordsList() {
      return keywords_;
    }
    /**
     * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder>
    getKeywordsOrBuilderList() {
      return keywords_;
    }
    /**
     * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
     */
    @java.lang.Override
    public int getKeywordsCount() {
      return keywords_.size();
    }
    /**
     * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
     */
    @java.lang.Override
    public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data getKeywords(int index) {
      return keywords_.get(index);
    }
    /**
     * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
     */
    @java.lang.Override
    public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder getKeywordsOrBuilder(
        int index) {
      return keywords_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getDataCount(); i++) {
        if (!getData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getKeywordsCount(); i++) {
        if (!getKeywords(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, subType_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(4, data_.get(i));
      }
      for (int i = 0; i < keywords_.size(); i++) {
        output.writeMessage(5, keywords_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, subType_);
      }
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, data_.get(i));
      }
      for (int i = 0; i < keywords_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, keywords_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord)) {
        return super.equals(obj);
      }
      org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord other = (org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord) obj;

      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (getTimestamp()
            != other.getTimestamp()) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (!getType()
            .equals(other.getType())) return false;
      }
      if (hasSubType() != other.hasSubType()) return false;
      if (hasSubType()) {
        if (!getSubType()
            .equals(other.getSubType())) return false;
      }
      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!getKeywordsList()
          .equals(other.getKeywordsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasSubType()) {
        hash = (37 * hash) + SUBTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getSubType().hashCode();
      }
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      if (getKeywordsCount() > 0) {
        hash = (37 * hash) + KEYWORDS_FIELD_NUMBER;
        hash = (53 * hash) + getKeywordsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code timeline.TimeLineRecord}
     */
    public static final class Builder extends
                                      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                                                                                              // @@protoc_insertion_point(builder_implements:timeline.TimeLineRecord)
                                                                                                  org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return org.sonatype.timeline.proto.TimeLineRecordProtos.internal_static_timeline_TimeLineRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return org.sonatype.timeline.proto.TimeLineRecordProtos.internal_static_timeline_TimeLineRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.class, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Builder.class);
      }

      // Construct using org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
            .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
          getKeywordsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        subType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          dataBuilder_.clear();
        }
        if (keywordsBuilder_ == null) {
          keywords_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          keywordsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return org.sonatype.timeline.proto.TimeLineRecordProtos.internal_static_timeline_TimeLineRecord_descriptor;
      }

      @java.lang.Override
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord getDefaultInstanceForType() {
        return org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.getDefaultInstance();
      }

      @java.lang.Override
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord build() {
        org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord buildPartial() {
        org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord result = new org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.subType_ = subType_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        if (keywordsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            keywords_ = java.util.Collections.unmodifiableList(keywords_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.keywords_ = keywords_;
        } else {
          result.keywords_ = keywordsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord) {
          return mergeFrom((org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord other) {
        if (other == org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000002;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasSubType()) {
          bitField0_ |= 0x00000004;
          subType_ = other.subType_;
          onChanged();
        }
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000008);
              dataBuilder_ =
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                      getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        if (keywordsBuilder_ == null) {
          if (!other.keywords_.isEmpty()) {
            if (keywords_.isEmpty()) {
              keywords_ = other.keywords_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureKeywordsIsMutable();
              keywords_.addAll(other.keywords_);
            }
            onChanged();
          }
        } else {
          if (!other.keywords_.isEmpty()) {
            if (keywordsBuilder_.isEmpty()) {
              keywordsBuilder_.dispose();
              keywordsBuilder_ = null;
              keywords_ = other.keywords_;
              bitField0_ = (bitField0_ & ~0x00000010);
              keywordsBuilder_ =
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                      getKeywordsFieldBuilder() : null;
            } else {
              keywordsBuilder_.addAllMessages(other.keywords_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getDataCount(); i++) {
          if (!getData(i).isInitialized()) {
            return false;
          }
        }
        for (int i = 0; i < getKeywordsCount(); i++) {
          if (!getKeywords(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 1;</code>
       * @return Whether the timestamp field is set.
       */
      @java.lang.Override
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>optional string type = 2;</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string type = 2;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string type = 2;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
      getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 2;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object subType_ = "";
      /**
       * <code>optional string subType = 3;</code>
       * @return Whether the subType field is set.
       */
      public boolean hasSubType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string subType = 3;</code>
       * @return The subType.
       */
      public java.lang.String getSubType() {
        java.lang.Object ref = subType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            subType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string subType = 3;</code>
       * @return The bytes for subType.
       */
      public com.google.protobuf.ByteString
      getSubTypeBytes() {
        java.lang.Object ref = subType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string subType = 3;</code>
       * @param value The subType to set.
       * @return This builder for chaining.
       */
      public Builder setSubType(
          java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        subType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string subType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        subType_ = getDefaultInstance().getSubType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string subType = 3;</code>
       * @param value The bytes for subType to set.
       * @return This builder for chaining.
       */
      public Builder setSubTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        subType_ = value;
        onChanged();
        return this;
      }

      private java.util.List<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data> data_ =
          java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          data_ = new java.util.ArrayList<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data>(data_);
          bitField0_ |= 0x00000008;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder> dataBuilder_;

      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public java.util.List<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public Builder setData(
          int index, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public Builder setData(
          int index, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public Builder addData(org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public Builder addData(
          int index, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public Builder addData(
          org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public Builder addData(
          int index, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public java.util.List<? extends org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder>
      getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.getDefaultInstance());
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.getDefaultInstance());
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data data = 4;</code>
       */
      public java.util.List<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder>
      getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder>
      getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder>(
              data_,
              ((bitField0_ & 0x00000008) != 0),
              getParentForChildren(),
              isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      private java.util.List<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data> keywords_ =
          java.util.Collections.emptyList();
      private void ensureKeywordsIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          keywords_ = new java.util.ArrayList<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data>(keywords_);
          bitField0_ |= 0x00000010;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder> keywordsBuilder_;

      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public java.util.List<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data> getKeywordsList() {
        if (keywordsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(keywords_);
        } else {
          return keywordsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public int getKeywordsCount() {
        if (keywordsBuilder_ == null) {
          return keywords_.size();
        } else {
          return keywordsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data getKeywords(int index) {
        if (keywordsBuilder_ == null) {
          return keywords_.get(index);
        } else {
          return keywordsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public Builder setKeywords(
          int index, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data value) {
        if (keywordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeywordsIsMutable();
          keywords_.set(index, value);
          onChanged();
        } else {
          keywordsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public Builder setKeywords(
          int index, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder builderForValue) {
        if (keywordsBuilder_ == null) {
          ensureKeywordsIsMutable();
          keywords_.set(index, builderForValue.build());
          onChanged();
        } else {
          keywordsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public Builder addKeywords(org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data value) {
        if (keywordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeywordsIsMutable();
          keywords_.add(value);
          onChanged();
        } else {
          keywordsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public Builder addKeywords(
          int index, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data value) {
        if (keywordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeywordsIsMutable();
          keywords_.add(index, value);
          onChanged();
        } else {
          keywordsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public Builder addKeywords(
          org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder builderForValue) {
        if (keywordsBuilder_ == null) {
          ensureKeywordsIsMutable();
          keywords_.add(builderForValue.build());
          onChanged();
        } else {
          keywordsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public Builder addKeywords(
          int index, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder builderForValue) {
        if (keywordsBuilder_ == null) {
          ensureKeywordsIsMutable();
          keywords_.add(index, builderForValue.build());
          onChanged();
        } else {
          keywordsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public Builder addAllKeywords(
          java.lang.Iterable<? extends org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data> values) {
        if (keywordsBuilder_ == null) {
          ensureKeywordsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, keywords_);
          onChanged();
        } else {
          keywordsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public Builder clearKeywords() {
        if (keywordsBuilder_ == null) {
          keywords_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          keywordsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public Builder removeKeywords(int index) {
        if (keywordsBuilder_ == null) {
          ensureKeywordsIsMutable();
          keywords_.remove(index);
          onChanged();
        } else {
          keywordsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder getKeywordsBuilder(
          int index) {
        return getKeywordsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder getKeywordsOrBuilder(
          int index) {
        if (keywordsBuilder_ == null) {
          return keywords_.get(index);  } else {
          return keywordsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public java.util.List<? extends org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder>
      getKeywordsOrBuilderList() {
        if (keywordsBuilder_ != null) {
          return keywordsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(keywords_);
        }
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder addKeywordsBuilder() {
        return getKeywordsFieldBuilder().addBuilder(
            org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.getDefaultInstance());
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder addKeywordsBuilder(
          int index) {
        return getKeywordsFieldBuilder().addBuilder(
            index, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.getDefaultInstance());
      }
      /**
       * <code>repeated .timeline.TimeLineRecord.Data keywords = 5;</code>
       */
      public java.util.List<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder>
      getKeywordsBuilderList() {
        return getKeywordsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder>
      getKeywordsFieldBuilder() {
        if (keywordsBuilder_ == null) {
          keywordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.DataOrBuilder>(
              keywords_,
              ((bitField0_ & 0x00000010) != 0),
              getParentForChildren(),
              isClean());
          keywords_ = null;
        }
        return keywordsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:timeline.TimeLineRecord)
    }

    // @@protoc_insertion_point(class_scope:timeline.TimeLineRecord)
    private static final org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord();
    }

    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TimeLineRecord>
        PARSER = new com.google.protobuf.AbstractParser<TimeLineRecord>() {
      @java.lang.Override
      public TimeLineRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TimeLineRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TimeLineRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TimeLineRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_timeline_TimeLineRecord_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_timeline_TimeLineRecord_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_timeline_TimeLineRecord_Data_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_timeline_TimeLineRecord_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
        "\n\024timelinerecord.proto\022\010timeline\"\304\001\n\016Tim" +
            "eLineRecord\022\021\n\ttimestamp\030\001 \001(\003\022\014\n\004type\030\002" +
            " \001(\t\022\017\n\007subType\030\003 \001(\t\022+\n\004data\030\004 \003(\0132\035.ti" +
            "meline.TimeLineRecord.Data\022/\n\010keywords\030\005" +
            " \003(\0132\035.timeline.TimeLineRecord.Data\032\"\n\004D" +
            "ata\022\013\n\003key\030\001 \002(\t\022\r\n\005value\030\002 \001(\tB3\n\033org.s" +
            "onatype.timeline.protoB\024TimeLineRecordPr" +
            "otos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
            });
    internal_static_timeline_TimeLineRecord_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_timeline_TimeLineRecord_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_timeline_TimeLineRecord_descriptor,
        new java.lang.String[] { "Timestamp", "Type", "SubType", "Data", "Keywords", });
    internal_static_timeline_TimeLineRecord_Data_descriptor =
        internal_static_timeline_TimeLineRecord_descriptor.getNestedTypes().get(0);
    internal_static_timeline_TimeLineRecord_Data_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_timeline_TimeLineRecord_Data_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
