/*
 * Sonatype Nexus (TM) Open Source Version
 * Copyright (c) 2008-present Sonatype, Inc.
 * All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License Version 1.0,
 * which accompanies this distribution and is available at http://www.eclipse.org/legal/epl-v10.html.
 *
 * Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
 * of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
 * Eclipse Foundation. All other trademarks are the property of their respective owners.
 */
package org.sonatype.nexus.repository.rest;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import javax.ws.rs.core.UriInfo;

import org.sonatype.goodies.common.ComponentSupport;
import org.sonatype.nexus.common.text.Strings2;
import org.sonatype.nexus.repository.Repository;
import org.sonatype.nexus.repository.rest.internal.resources.RepositoryManagerRESTAdapter;
import org.sonatype.nexus.repository.search.DefaultSearchContribution;
import org.sonatype.nexus.repository.search.SearchContribution;
import org.sonatype.nexus.repository.search.SearchFilter;

import org.elasticsearch.index.query.BoolQueryBuilder;
import org.elasticsearch.index.query.QueryBuilder;
import org.elasticsearch.index.query.QueryBuilders;

import static com.google.common.base.Preconditions.checkNotNull;
import static java.util.Collections.singletonList;
import static java.util.stream.Collectors.toMap;
import static java.util.stream.Collectors.toSet;
import static java.util.stream.StreamSupport.stream;

/**
 * @since 3.7
 */
@Named
@Singleton
public class SearchUtils
    extends ComponentSupport
{
  private static final String CONTINUATION_TOKEN = "continuationToken";

  private static final String ASSET_PREFIX = "assets.";

  private final RepositoryManagerRESTAdapter repoAdapter;

  private final Map<String, String> searchParams;

  private final Map<String, String> assetSearchParams;

  private final Map<String, SearchContribution> searchContributions;

  private final SearchContribution defaultSearchContribution;

  @Inject
  public SearchUtils(final RepositoryManagerRESTAdapter repoAdapter,
                     final Map<String, SearchMappings> searchMappings,
                     final Map<String, SearchContribution> searchContributions)
  {
    this.repoAdapter = checkNotNull(repoAdapter);
    this.searchParams = checkNotNull(searchMappings).entrySet().stream()
        .flatMap(e -> stream(e.getValue().get().spliterator(), true))
        .collect(toMap(SearchMapping::getAlias, SearchMapping::getAttribute));
    this.assetSearchParams = searchParams.entrySet().stream()
        .filter(e -> e.getValue().startsWith(ASSET_PREFIX))
        .collect(toMap(Entry::getKey, Entry::getValue));
    this.searchContributions = checkNotNull(searchContributions);
    this.defaultSearchContribution = checkNotNull(searchContributions.get(DefaultSearchContribution.NAME));
  }

  public Map<String, String> getSearchParameters() {
    return searchParams;
  }

  public Map<String, String> getAssetSearchParameters() {
    return assetSearchParams;
  }

  public Repository getRepository(final String repository) {
    return repoAdapter.getRepository(repository);
  }

  /**
   * @since 3.15
   * @param searchFilters
   * @return a {@link QueryBuilder} for the provided search filters, the query will be generated by the {@link SearchContribution}s
   */
  public QueryBuilder buildQuery(final Collection<SearchFilter> searchFilters) {
    BoolQueryBuilder query = QueryBuilders.boolQuery();
    searchFilters.stream().filter(searchFilter -> !Strings2.isBlank(searchFilter.getValue())).forEach(searchFilter -> {
      SearchContribution searchContribution = searchContributions
          .getOrDefault(searchFilter.getProperty(), defaultSearchContribution);

      searchContribution.contribute(query, searchFilter.getProperty(), searchFilter.getValue());
    });

    log.debug("Query: {}", query);

    return query;
  }

  /**
   * Builds a {@link QueryBuilder} based on configured search parameters.
   *
   * @param uriInfo {@link UriInfo} to extract query parameters from
   */
  public QueryBuilder buildQuery(final UriInfo uriInfo) {
    Collection<SearchFilter> searchFilters = convertParameters(uriInfo, singletonList(CONTINUATION_TOKEN));
    return buildQuery(searchFilters);
  }

  public QueryBuilder buildQuery(final UriInfo uriInfo, final List<String> parameters) {
    ArrayList<String> filterParameters = new ArrayList<>();
    filterParameters.add(CONTINUATION_TOKEN);
    filterParameters.addAll(parameters);
    return buildQuery(convertParameters(uriInfo, filterParameters));
  }

  private Collection<SearchFilter> convertParameters(final UriInfo uriInfo, final List<String> keys) {
    return uriInfo.getQueryParameters().entrySet().stream()
        .filter(entry -> !keys.contains(entry.getKey()))
        .map(entry -> entry.getValue().stream().map(value -> {
          String key = searchParams.getOrDefault(entry.getKey(), entry.getKey());
          return new SearchFilter(key, value);
        }).collect(toSet())).flatMap(Collection::stream).collect(toSet());
  }

  public boolean isAssetSearchParam(final String assetSearchParam) {
    return assetSearchParams.containsKey(assetSearchParam) || isFullAssetAttributeName(assetSearchParam);
  }

  public boolean isFullAssetAttributeName(final String assetSearchParam) {
    return assetSearchParam.startsWith(ASSET_PREFIX);
  }

  public String getFullAssetAttributeName(final String key) {
    return isFullAssetAttributeName(key) ? key : getAssetSearchParameters().get(key);
  }
}
