/*
 * Sonatype Nexus (TM) Open Source Version
 * Copyright (c) 2008-present Sonatype, Inc.
 * All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License Version 1.0,
 * which accompanies this distribution and is available at http://www.eclipse.org/legal/epl-v10.html.
 *
 * Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
 * of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
 * Eclipse Foundation. All other trademarks are the property of their respective owners.
 */
package org.sonatype.nexus.upgrade.datastore.internal.steps;

import java.sql.Connection;

import org.sonatype.goodies.testsupport.TestSupport;
import org.sonatype.nexus.testdb.DataSessionRule;

import org.junit.Rule;
import org.junit.Test;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.sonatype.nexus.datastore.api.DataStoreManager.DEFAULT_DATASTORE_NAME;

public class RemoveFreezeMigrationStep_2_111Test
    extends TestSupport
{
  @Rule
  public DataSessionRule dataSessionRule = new DataSessionRule(DEFAULT_DATASTORE_NAME);

  private final RemoveFreezeMigrationStep_2_111 underTest = new RemoveFreezeMigrationStep_2_111();

  @Test
  public void testMigrate_dropsTableWhenExists() throws Exception {
    try (Connection connection = dataSessionRule.openConnection(DEFAULT_DATASTORE_NAME)) {
      // Create the freeze_requests table
      underTest.runStatement(connection, """
          CREATE TABLE IF NOT EXISTS freeze_requests (
            id           INT                      GENERATED BY DEFAULT AS IDENTITY,
            token        VARCHAR(100)             NULL,
            reason       VARCHAR                  NULL,
            frozen_by    VARCHAR(200)             NULL,
            frozen_by_ip VARCHAR(45)              NULL,
            frozen_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

            CONSTRAINT pk_freeze_requests_id PRIMARY KEY (id),
            CONSTRAINT uk_freeze_requests_token UNIQUE (token)
          );
          """);

      // Verify table exists
      assertTrue("freeze_requests table should exist before migration",
          underTest.tableExists(connection, "freeze_requests"));

      // Run migration
      underTest.migrate(connection);

      // Verify table no longer exists
      assertFalse("freeze_requests table should be dropped after migration",
          underTest.tableExists(connection, "freeze_requests"));
    }
  }

  @Test
  public void testMigrate_noErrorWhenTableDoesNotExist() throws Exception {
    try (Connection connection = dataSessionRule.openConnection(DEFAULT_DATASTORE_NAME)) {
      // Verify table doesn't exist
      assertFalse("freeze_requests table should not exist",
          underTest.tableExists(connection, "freeze_requests"));

      // Run migration - should not throw
      underTest.migrate(connection);

      // Verify table still doesn't exist
      assertFalse("freeze_requests table should still not exist",
          underTest.tableExists(connection, "freeze_requests"));
    }
  }

  @Test
  public void testMigrate_isIdempotent() throws Exception {
    try (Connection connection = dataSessionRule.openConnection(DEFAULT_DATASTORE_NAME)) {
      // Create the freeze_requests table
      underTest.runStatement(connection, """
          CREATE TABLE IF NOT EXISTS freeze_requests (
            id           INT                      GENERATED BY DEFAULT AS IDENTITY,
            token        VARCHAR(100)             NULL,
            reason       VARCHAR                  NULL,
            frozen_by    VARCHAR(200)             NULL,
            frozen_by_ip VARCHAR(45)              NULL,
            frozen_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

            CONSTRAINT pk_freeze_requests_id PRIMARY KEY (id),
            CONSTRAINT uk_freeze_requests_token UNIQUE (token)
          );
          """);

      // Run migration twice
      underTest.migrate(connection);
      underTest.migrate(connection);

      // Verify table doesn't exist after multiple runs
      assertFalse("freeze_requests table should be dropped after multiple migrations",
          underTest.tableExists(connection, "freeze_requests"));
    }
  }
}
